name: Deploy Hugo

on: 
  push:
    branches:
      - main
    
permission:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: CheckOut
        uses: action/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup Hugo
        uses: peaceiris/action-hugo@v2
        with:
          hugo-version: latest
          extend: true
      
      - name: Build
        run: hugo
      
      - name: Upload
        uses: actions/Upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
    
    permission:
      pages: write
      id-token: write

    steps:

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4